### ISSUE TITLE
XSS not allowed?

### ISSUE THREAD

**Issue by docfate111** [stanford-web-security/assign1#2]
Hello thank you so much for putting these resources online.
I am struggling with the first XSS problem. Looking from [here](https://github.com/NagliNagli/Stanford-CS253-Assignment-1-Solution/blob/master/SOLUTIONS.md) my guess that I need to put <script>success</script> in the box at the bottom or in the URL is correct? However when I try in Google Chrome and Firefox it doesn't work? Also, the linked iframe doesn't work on my computer at http://localhost:4000/1. Maybe I am missing something or I set up browser wrong?
<img width="776" alt="Screen Shot 2020-12-10 at 11 34 11 PM" src="https://user-images.githubusercontent.com/24590069/101867195-39e22600-3b40-11eb-904d-1bb3c786bfed.png">

![2020-12-10 23 28 09](https://user-images.githubusercontent.com/24590069/101867330-7f9eee80-3b40-11eb-8e1e-910ab9f40801.gif)

**Comment by feross** [comment]
I renewed the caloogle domain so this should work again.
